# Generated by Django 5.2.6 on 2025-09-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_joined_date_alter_member_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Members',
        ),
    ]
