# Generated by Django 5.2.6 on 2025-09-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_member_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
